version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    commit-message:
      prefix: "chore(deps)"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
