version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    commit-message:
      prefix: "chore(deps)"
    target-branch: "develop"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
          - "minor"

      development-dependencies:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"

    # Major versions should be updated manually, to avoid breaking changes.
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
