graph TD
	QHZT("@nimara/codegen#build") --> ETTT("@nimara/config#build")
	QHZT("@nimara/codegen#build") --> JEGP("@nimara/config#codegen")
	EMLE("@nimara/codegen#codegen") --> JEGP("@nimara/config#codegen")
	ETTT("@nimara/config#build") --> LRHC("___ROOT___")
	JEGP("@nimara/config#codegen") --> LRHC("___ROOT___")
	GLAO("@nimara/domain#build") --> ETTT("@nimara/config#build")
	GLAO("@nimara/domain#build") --> JEGP("@nimara/config#codegen")
	VELR("@nimara/domain#codegen") --> JEGP("@nimara/config#codegen")
	TXWC("@nimara/features#build") --> ETTT("@nimara/config#build")
	TXWC("@nimara/features#build") --> JEGP("@nimara/config#codegen")
	TXWC("@nimara/features#build") --> GLAO("@nimara/domain#build")
	TXWC("@nimara/features#build") --> VELR("@nimara/domain#codegen")
	TXWC("@nimara/features#build") --> WCIN("@nimara/foundation#build")
	TXWC("@nimara/features#build") --> TPBW("@nimara/foundation#codegen")
	TXWC("@nimara/features#build") --> BHWE("@nimara/i18n#build")
	TXWC("@nimara/features#build") --> MKNG("@nimara/i18n#codegen")
	TXWC("@nimara/features#build") --> IRKD("@nimara/infrastructure#build")
	TXWC("@nimara/features#build") --> UWBQ("@nimara/infrastructure#codegen")
	TXWC("@nimara/features#build") --> FBWM("@nimara/ui#build")
	TXWC("@nimara/features#build") --> NRTE("@nimara/ui#codegen")
	GVMR("@nimara/features#codegen") --> JEGP("@nimara/config#codegen")
	GVMR("@nimara/features#codegen") --> VELR("@nimara/domain#codegen")
	GVMR("@nimara/features#codegen") --> TPBW("@nimara/foundation#codegen")
	GVMR("@nimara/features#codegen") --> MKNG("@nimara/i18n#codegen")
	GVMR("@nimara/features#codegen") --> UWBQ("@nimara/infrastructure#codegen")
	GVMR("@nimara/features#codegen") --> NRTE("@nimara/ui#codegen")
	WCIN("@nimara/foundation#build") --> QHZT("@nimara/codegen#build")
	WCIN("@nimara/foundation#build") --> EMLE("@nimara/codegen#codegen")
	WCIN("@nimara/foundation#build") --> ETTT("@nimara/config#build")
	WCIN("@nimara/foundation#build") --> JEGP("@nimara/config#codegen")
	WCIN("@nimara/foundation#build") --> GLAO("@nimara/domain#build")
	WCIN("@nimara/foundation#build") --> VELR("@nimara/domain#codegen")
	WCIN("@nimara/foundation#build") --> BHWE("@nimara/i18n#build")
	WCIN("@nimara/foundation#build") --> MKNG("@nimara/i18n#codegen")
	WCIN("@nimara/foundation#build") --> FBWM("@nimara/ui#build")
	WCIN("@nimara/foundation#build") --> NRTE("@nimara/ui#codegen")
	TPBW("@nimara/foundation#codegen") --> EMLE("@nimara/codegen#codegen")
	TPBW("@nimara/foundation#codegen") --> JEGP("@nimara/config#codegen")
	TPBW("@nimara/foundation#codegen") --> VELR("@nimara/domain#codegen")
	TPBW("@nimara/foundation#codegen") --> MKNG("@nimara/i18n#codegen")
	TPBW("@nimara/foundation#codegen") --> NRTE("@nimara/ui#codegen")
	BHWE("@nimara/i18n#build") --> ETTT("@nimara/config#build")
	BHWE("@nimara/i18n#build") --> JEGP("@nimara/config#codegen")
	MKNG("@nimara/i18n#codegen") --> JEGP("@nimara/config#codegen")
	IRKD("@nimara/infrastructure#build") --> QHZT("@nimara/codegen#build")
	IRKD("@nimara/infrastructure#build") --> EMLE("@nimara/codegen#codegen")
	IRKD("@nimara/infrastructure#build") --> ETTT("@nimara/config#build")
	IRKD("@nimara/infrastructure#build") --> JEGP("@nimara/config#codegen")
	IRKD("@nimara/infrastructure#build") --> GLAO("@nimara/domain#build")
	IRKD("@nimara/infrastructure#build") --> VELR("@nimara/domain#codegen")
	IRKD("@nimara/infrastructure#build") --> WCIN("@nimara/foundation#build")
	IRKD("@nimara/infrastructure#build") --> TPBW("@nimara/foundation#codegen")
	UWBQ("@nimara/infrastructure#codegen") --> EMLE("@nimara/codegen#codegen")
	UWBQ("@nimara/infrastructure#codegen") --> JEGP("@nimara/config#codegen")
	UWBQ("@nimara/infrastructure#codegen") --> VELR("@nimara/domain#codegen")
	UWBQ("@nimara/infrastructure#codegen") --> TPBW("@nimara/foundation#codegen")
	FBWM("@nimara/ui#build") --> ETTT("@nimara/config#build")
	FBWM("@nimara/ui#build") --> JEGP("@nimara/config#codegen")
	NRTE("@nimara/ui#codegen") --> JEGP("@nimara/config#codegen")
	ITTZ("storefront#build") --> QHZT("@nimara/codegen#build")
	ITTZ("storefront#build") --> EMLE("@nimara/codegen#codegen")
	ITTZ("storefront#build") --> ETTT("@nimara/config#build")
	ITTZ("storefront#build") --> JEGP("@nimara/config#codegen")
	ITTZ("storefront#build") --> GLAO("@nimara/domain#build")
	ITTZ("storefront#build") --> VELR("@nimara/domain#codegen")
	ITTZ("storefront#build") --> TXWC("@nimara/features#build")
	ITTZ("storefront#build") --> GVMR("@nimara/features#codegen")
	ITTZ("storefront#build") --> WCIN("@nimara/foundation#build")
	ITTZ("storefront#build") --> TPBW("@nimara/foundation#codegen")
	ITTZ("storefront#build") --> BHWE("@nimara/i18n#build")
	ITTZ("storefront#build") --> MKNG("@nimara/i18n#codegen")
	ITTZ("storefront#build") --> IRKD("@nimara/infrastructure#build")
	ITTZ("storefront#build") --> UWBQ("@nimara/infrastructure#codegen")
	ITTZ("storefront#build") --> FBWM("@nimara/ui#build")
	ITTZ("storefront#build") --> NRTE("@nimara/ui#codegen")
