import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

// Docusaurus loads the sidebar configuration from the module's default export.
// eslint-disable-next-line import/no-default-export
export default sidebars;
