import { HomepageAttribute } from "./types";

export const HOMEPAGE_ATTRIBUTES: HomepageAttribute[] = [
  {
    name: "Carousel products",
    type: "PAGE_TYPE",
    inputType: "REFERENCE",
    entityType: "PRODUCT",
    slug: "carousel-products",
    source: "carouselProducts",
  },
  {
    name: "Homepage banner button text",
    type: "PAGE_TYPE",
    inputType: "PLAIN_TEXT",
    slug: "homepage-banner-button-text",
    source: "bannerButtonText",
  },
  {
    name: "Homepage banner header",
    type: "PAGE_TYPE",
    inputType: "PLAIN_TEXT",
    slug: "homepage-banner-header",
    source: "bannerHeader",
  },
  {
    name: "Homepage banner image",
    type: "PAGE_TYPE",
    inputType: "FILE",
    slug: "homepage-banner-image",
    source: "bannerImageUrl",
  },
  {
    name: "Homepage button text",
    type: "PAGE_TYPE",
    inputType: "PLAIN_TEXT",
    slug: "homepage-button-text",
    source: "buttonText",
  },
  {
    name: "Homepage grid item header",
    type: "PAGE_TYPE",
    inputType: "PLAIN_TEXT",
    slug: "homepage-grid-item-header",
    source: "gridItems.header",
  },
  {
    name: "Homepage grid item image",
    type: "PAGE_TYPE",
    inputType: "FILE",
    slug: "homepage-grid-item-image",
    source: "gridItems.imageUrl",
  },
  {
    name: "Homepage grid item subheader",
    type: "PAGE_TYPE",
    inputType: "PLAIN_TEXT",
    slug: "homepage-grid-item-subheader",
    source: "gridItems.subheader",
  },
  {
    name: "Homepage grid item header font color",
    type: "PAGE_TYPE",
    inputType: "SWATCH",
    slug: "homepage-grid-item-header-font-color",
    source: "gridItems.headerFontColor",
    values: [{ name: "dark", value: "#000000" }, { name: "light", value: "#ffffff" }],
  },
  {
    name: "Homepage grid item subheader font color",
    type: "PAGE_TYPE",
    inputType: "SWATCH",
    slug: "homepage-grid-item-subheader-font-color",
    source: "gridItems.subheaderFontColor",
    values: [{ name: "dark", value: "#000000" }, { name: "light", value: "#ffffff" }],
  },
];
