/**
 * Storefront preflight.
 *
 * Interactive (TTY): a @clack/prompts wizard — pick a provider per swappable
 * capability, see the required env, and optionally write an example env file.
 * Non-interactive (CI / piped / `--report`): a read-only status report.
 *
 * Required env is derived from the REAL provider config schemas: this script is
 * run with `tsx`, so it imports the infrastructure provider manifests and uses
 * each provider's Zod `configSchema` to determine required/missing keys — no
 * hand-maintained list and no source-parsing heuristic.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import {
  cancel,
  confirm,
  intro,
  isCancel,
  note,
  outro,
  select,
  text,
} from "@clack/prompts";

import { cmsPageProviders } from "@nimara/infrastructure/cms-page/select";
import { searchProviders } from "@nimara/infrastructure/search/select";

type SafeParseResult = {
  error?: { issues: { path: PropertyKey[] }[] };
  success: boolean;
};

type Provider = {
  configSchema?: { safeParse: (value: unknown) => SafeParseResult };
  id: string;
};

type Capability = {
  name: string;
  providers: readonly Provider[];
  selectVar: string;
};

const scriptDir = dirname(fileURLToPath(import.meta.url));
const envPath = resolve(scriptDir, "..", ".env");

/** Minimal KEY=VALUE parser — good enough for a status report. */
const parseEnvFile = (path: string): Record<string, string> => {
  if (!existsSync(path)) {
    return {};
  }

  const out: Record<string, string> = {};

  for (const rawLine of readFileSync(path, "utf8").split("\n")) {
    const line = rawLine.trim();

    if (!line || line.startsWith("#")) {
      continue;
    }

    const eq = line.indexOf("=");

    if (eq === -1) {
      continue;
    }

    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    out[key] = value;
  }

  return out;
};

const env: Record<string, string | undefined> = {
  ...parseEnvFile(envPath),
  ...process.env,
};
const has = (key: string) =>
  Boolean(env[key] && String(env[key]).trim() !== "");
const isProduction = env.NEXT_PUBLIC_ENVIRONMENT === "PRODUCTION";
const saleorConfigured = has("NEXT_PUBLIC_SALEOR_API_URL");

const CAPABILITIES: Capability[] = [
  { name: "Search", selectVar: "SEARCH_SERVICE", providers: searchProviders },
  {
    name: "CMS (pages + menus)",
    selectVar: "CMS_SERVICE",
    providers: cmsPageProviders,
  },
];

/**
 * Env keys the provider's Zod schema flags for the given candidate env
 * (missing or invalid). With `{}` this yields the provider's required keys.
 */
const issuesFor = (
  provider: Provider,
  candidate: Record<string, string | undefined>,
): string[] => {
  if (!provider.configSchema) {
    return [];
  }

  const result = provider.configSchema.safeParse(candidate);

  if (result.success || !result.error) {
    return [];
  }

  return [
    ...new Set(result.error.issues.map((issue) => String(issue.path[0]))),
  ];
};

const requiredKeys = (provider: Provider): string[] => issuesFor(provider, {});

const orderProviders = (providers: readonly Provider[]): Provider[] =>
  [...providers].sort((a, b) => {
    const rank = (id: string) => (id === "saleor" ? 0 : id === "dummy" ? 2 : 1);

    return rank(a.id) - rank(b.id) || a.id.localeCompare(b.id);
  });

/** Builds the example env file for the chosen providers. */
const renderEnvFile = (
  selections: { capability: Capability; provider: Provider }[],
): string => {
  const lines = [
    "# Generated by `pnpm preflight` — integration selection",
    `# ${selections.map((s) => `${s.capability.selectVar}=${s.provider.id}`).join(", ")}`,
    "",
    "# --- Provider selection (server-side) ---",
    ...selections.map((s) => `${s.capability.selectVar}=${s.provider.id}`),
    "",
    "# --- Required env for the selected providers ---",
  ];

  const seen = new Set<string>();

  for (const { provider } of selections) {
    for (const key of requiredKeys(provider)) {
      if (!seen.has(key)) {
        seen.add(key);
        lines.push(`${key}=`);
      }
    }
  }

  if (!seen.size) {
    lines.push("# (dummy providers need no extra env)");
  }

  return lines.join("\n") + "\n";
};

// --- Non-interactive status report --------------------------------------------

const renderReport = (): void => {
  const ON = "\x1b[32m●  ON\x1b[0m";
  const OFF = "\x1b[90m○ OFF\x1b[0m";

  const features = [
    { name: "Backend (Saleor)", on: saleorConfigured },
    { name: "Customer login", on: has("AUTH_SECRET") },
    {
      name: "Checkout (Stripe)",
      on:
        has("NEXT_PUBLIC_PAYMENT_APP_ID") &&
        has("NEXT_PUBLIC_STRIPE_PUBLIC_KEY") &&
        has("STRIPE_SECRET_KEY"),
    },
    {
      name: "Marketplace",
      on:
        has("NEXT_PUBLIC_MARKETPLACE_ENABLED") &&
        env.NEXT_PUBLIC_MARKETPLACE_ENABLED !== "false",
    },
  ];

  const pad = Math.max(...features.map((f) => f.name.length));

  console.log("\nStorefront preflight — feature status\n");

  for (const feature of features) {
    console.log(`  ${feature.on ? ON : OFF}  ${feature.name.padEnd(pad)}`);
  }

  console.log("\nIntegrations (swappable providers)");

  const intPad = Math.max(...CAPABILITIES.map((c) => c.name.length));

  for (const capability of CAPABILITIES) {
    const label = capability.name.padEnd(intPad);
    const requested = env[capability.selectVar] || "saleor";
    const provider = capability.providers.find((p) => p.id === requested);

    if (!provider) {
      const allowed = capability.providers.map((p) => p.id).join(" | ");

      console.log(
        `  \x1b[33m⚠\x1b[0m  ${label}  ${capability.selectVar}="${requested}" unknown (expected: ${allowed})`,
      );
      continue;
    }

    if (requested === "saleor" && !saleorConfigured) {
      console.log(
        isProduction
          ? `  ${OFF}  ${label}  empty (Saleor unconfigured in production)`
          : `  \x1b[36m◐ DUMMY\x1b[0m  ${label}  sample data (set ${capability.selectVar})`,
      );
      continue;
    }

    const missing = issuesFor(provider, env);

    console.log(
      missing.length
        ? `  \x1b[31m✗ MISS\x1b[0m  ${label}  ${requested} — missing: ${missing.join(", ")}`
        : `  ${ON}  ${label}  ${requested}`,
    );
  }

  console.log(
    "\n\x1b[90mTip: run `pnpm preflight` in a terminal to pick providers interactively.\x1b[0m\n",
  );
};

// --- Interactive wizard -------------------------------------------------------

const exitIfCancelled = <T,>(value: T | symbol): T => {
  if (isCancel(value)) {
    cancel("Cancelled.");
    process.exit(0);
  }

  return value;
};

const runWizard = async (): Promise<void> => {
  intro("Nimara storefront — integration setup");

  const selections: { capability: Capability; provider: Provider }[] = [];

  for (const capability of CAPABILITIES) {
    const ordered = orderProviders(capability.providers);
    const choice = exitIfCancelled(
      await select({
        message: `${capability.name} provider`,
        initialValue: "saleor",
        options: ordered.map((provider) => ({
          value: provider.id,
          label: provider.id,
          hint: requiredKeys(provider).join(", ") || "no env required",
        })),
      }),
    );

    const provider = capability.providers.find((p) => p.id === choice);

    if (provider) {
      selections.push({ capability, provider });
    }
  }

  const summary = selections
    .flatMap(({ capability, provider }) => [
      `${capability.selectVar}=${provider.id}`,
      ...requiredKeys(provider).map((key) => `${key}=  (required)`),
    ])
    .join("\n");

  note(summary, "Required environment");

  const content = renderEnvFile(selections);
  const defaultTarget = "apps/storefront/.env.local";
  const target =
    exitIfCancelled(
      await text({
        message: "Save example env file to (enter to accept default)",
        placeholder: defaultTarget,
        defaultValue: defaultTarget,
      }),
    ).trim() || defaultTarget;

  const absolute = resolve(process.cwd(), target);

  if (existsSync(absolute)) {
    const overwrite = exitIfCancelled(
      await confirm({
        message: `${target} exists — overwrite?`,
        initialValue: false,
      }),
    );

    if (!overwrite) {
      outro("Not written.");

      return;
    }
  }

  writeFileSync(absolute, content);
  outro(`✓ wrote ${target}`);
};

// --- Entry --------------------------------------------------------------------

const printBanner = (): void => {
  const art = [
    " ███╗   ██╗██╗███╗   ███╗ █████╗ ██████╗  █████╗",
    " ████╗  ██║██║████╗ ████║██╔══██╗██╔══██╗██╔══██╗",
    " ██╔██╗ ██║██║██╔████╔██║███████║██████╔╝███████║",
    " ██║╚██╗██║██║██║╚██╔╝██║██╔══██║██╔══██╗██╔══██║",
    " ██║ ╚████║██║██║ ╚═╝ ██║██║  ██║██║  ██║██║  ██║",
    " ╚═╝  ╚═══╝╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝",
  ].join("\n");

  console.log(`\x1b[36m\n${art}\x1b[0m`);
  console.log("\x1b[90m  composable commerce — storefront preflight\x1b[0m");
};

printBanner();

const forceReport = process.argv.includes("--report");

if (!forceReport && process.stdin.isTTY) {
  await runWizard();
} else {
  renderReport();
}
