export const TRANSACTION_EVENT_TYPE = [
  "AUTHORIZATION_ACTION_REQUIRED",
  "AUTHORIZATION_ADJUSTMENT",
  "AUTHORIZATION_FAILURE",
  "AUTHORIZATION_REQUEST",
  "AUTHORIZATION_SUCCESS",
  "CANCEL_FAILURE",
  "CANCEL_REQUEST",
  "CANCEL_SUCCESS",
  "CHARGE_ACTION_REQUIRED",
  "CHARGE_BACK",
  "CHARGE_FAILURE",
  "CHARGE_REQUEST",
  "CHARGE_SUCCESS",
  "INFO",
  "REFUND_FAILURE",
  "REFUND_REQUEST",
  "REFUND_REVERSE",
  "REFUND_SUCCESS",
] as const;

export type TransactionEventType = (typeof TRANSACTION_EVENT_TYPE)[number];
